### ISSUE TITLE
sql脚本缺少初始化数据

### ISSUE THREAD

**Issue by jiafuweiJava** [leijinjun/sms-bomb#2]
s_sms_url 表中缺少数据，导致运行的程序无法发送短信出去。

**Comment by leijinjun** [comment]
恕不能提供数据
发件人: fuwei jia
发送时间: 2021年3月25日 10:37
收件人: leijinjun/sms-bomb
抄送: Subscribed
主题: [leijinjun/sms-bomb] sql脚本缺少初始化数据 (#2)

s_sms_url 表中缺少数据，导致运行的程序无法发送短信出去。
